language: ruby
notifications:
  email: false
  slack:
    secure: sYPZKix0grVFgXpuxIKjDnaixKcD8p7dEtaGBHlZtl7mF6BOUHpT2pTHqygSne68O3ihUjCcri+JsLgOqnFEcAlmN8nV4NWVo9gNb4/3786L1FNOOvEzbpa9z/g8dlHL+2tMHtg3+NgWWBf88oqyQJppuzbaOxt/hmIjjad4qm8GPtrFTBpA631yTVMB8JGWSxqeJPYrYkThYufrwgqNf0+nfrXBIuXgVcyqM8UtMiDtyU/1QCZ+LBNMyslvm+AjcqUkKQQJFqrIsnuh6BnDC+PUXEfXYLb7EDIBwHPl3B2MifPkdDN93QBdCr8EIwYu9i2nSlCGubJrp//Jl4S90y+Yvpgt5SFtp3DMwy7aVeQI47wDTA7ys+UI+BsifRJEHiQuZCo1uGp7/s4R0b0FpjE6aGA8Osev4dtPM4qT2lVJqcEhVjd+2J/A7Ke/ZeGDGLnSZdTHPkUY3/qIddN2vG+Nh6y4XKIbFZcF4SFSBGl6/szBO+EgRjh3I797vTtIdkxDfWa9Wdni6lL3Z9HtssFVas9ibYAHobYTQcod3LCsHxdNnHm1/MFQXm1uEBHhmWSxGDp/RgCvXYWjqeXOroIwVYFPm1TSiIrYubEQIEc8JlGM+2QXz/wo/6idfyoplaPYogZEd/bzRqRpBOHnpE75Ib0b3B2RJF4GV4y9ue0=
cache: bundler
rvm:
- 2.4.0
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate db:test:prepare
script:
- bundle exec rake ci:tests
deploy:
  provider: heroku
  api_key:
    secure: rUyGQP9+ymiLnQDDmHi2qtiMMSvv2kVx2U1bmeMLbxwgJfVkNPMbGN9VB9HhsNlc7RshRHdJ/TgnaffW5hkzjL9rL+OOXOWbgYJuHZMV5KUIV+hWcHuiZEqzTY1O7bkF3x6SLlyhpHBrNO674KRKbKZ9Tv8K3fjIVig15Y+e/io4SXr23PH1FIt8n81Yyc6u7VQmqDUhnMh596NW+x8rNvKK/A+bkxYzBcQTm5UjfnZhwI0ajMzZhdhfW49UxLnxXI6H4Qni2sg7ujyVQT5RGnFMNS9uqBqrbpLRrsnpRml4Zuz/Sbthm33KsppwC1OiCo38QI8IP9BhAB+ua1TmqW1laUkwApBd3MxvxGJa2pX9OKYD9UQ5NImXX2dMEOUUsuIkRy+HsvuqzM37F4PXow3xmlTcxSs/8FVOa6KFXEKqAgmdOska+XiFT4KHVMueqSPUNB1vEPlK/yUMsKFP9EXXYa18UMNkV2OwIhbxL2+kWvwz4YBfRwnd7sgXPm6nP/MKELjXGm/4vcj9ajHpfNrbvlUc7welYIp+U8p5weYz3WGRTY/ZgcFXu38fcwT77uP9veZYqYKxblyPyQS46Xm5f6cDA2/B1nWY8UGVEZQSLSDW5ADA4Y38oFcCDas22TOVQTHbBsi4fimjkcGS3iynntsDxYDG/VJsQYPmQx0=
  app: laundrytime
  on:
    repo: CraftAcademy/laundry_time
    branch: develop
  run: bundle exec rails db:migrate
