language: ruby
cache: bundler
rvm:
- 2.4.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
deploy:
  provider: heroku
  api_key:
    secure: kNlptCXK6qE7uCaxfcxBpXbJsZcqXo5kCAc9XEYulsdHR+UPQjeUpK5yejl0vOcc4AhmwnJdZkxpknJC1g4GY02gOvzucQzhQYxQGnbb+eJMS+QZeezIHof8qswZXLAdWz0vrEnLJknD9TaL4arvUI1gPfCqAXGM+SHwVOZlwONKNCaovphNXf6EyNFJF+EtMceYdhCyldn+3ONmuSW43nHl+K7zUm3VnkQWudgk2Bmc16zubTHlmxXBWm09o5e2M5rsZR79m7EkeTLWZM+6IqaVOLYAPxGWKeqf9RxH9d+HXpokKBaoxd6RIFgvJPa90z/ojpGOCxNkgd57Bhh+B7bQrDKqUFzbCC84Dgq1mbOx74mNt0xzVNku7t4G4uvqnZmsZG4biE/6rbQJ/9u5wekw3XJaqiMBxbHsv9sGsCpHHP/yXU1jpT5J+UyNRiSWAX1EPjPd0P2FgmO5ObqUYihaPh1wBuS7yAKrcK1I8McbhqIIt8ocWbbnaePOM6iHnFxrwQI4lXYSmKlm4VcIisubJvSXLr0t4d0uevnv1wiYDVgokepQ4mHgpFCzZw1QPt/whPaBdbDrmFuKCk37qmKv1ro3aYaFNWZRHYTEdWS12D4aa4ydCvPrb1qWrDCJN04rdkqwO4pmtbbolyh77gfJvYwDpuinQMerWTHvYxs=
  app: laundrytime
  on:
    repo: CraftAcademy/laundry_time
    branch: develop
