default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: laundry_time_development
test:
  <<: *default
  database: laundry_time_test

production:
  <<: *default
  database: laundry_time_production
  username: laundry_time
  password: <%= ENV['LAUNDRY_TIME_DATABASE_PASSWORD'] %>
